Update pelican.yml
add debug info about output and index.html

diff --git a/.github/workflows/pelican.yml b/.github/workflows/pelican.yml
--- a/.github/workflows/pelican.yml
+++ b/.github/workflows/pelican.yml
@@ -48,6 +48,9 @@ jobs:
             echo "::warning title=Invalid file permissions automatically fixed::$line"
           done
 
+      - name: Debug output folder contents
+        run: ls -lah output && cat output/index.html || echo "index.html not found"
+
       - name: Upload site artifact
         uses: actions/upload-pages-artifact@v3
         with:
